/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.imgseek.imgdb.core;

public class ClusterVector {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ClusterVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ClusterVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      imgdbJNI.delete_ClusterVector(swigCPtr);
    }
    swigCPtr = 0;
  }

  public ClusterVector() {
    this(imgdbJNI.new_ClusterVector__SWIG_0(), true);
  }

  public ClusterVector(long n) {
    this(imgdbJNI.new_ClusterVector__SWIG_1(n), true);
  }

  public long size() {
    return imgdbJNI.ClusterVector_size(swigCPtr, this);
  }

  public long capacity() {
    return imgdbJNI.ClusterVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    imgdbJNI.ClusterVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return imgdbJNI.ClusterVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    imgdbJNI.ClusterVector_clear(swigCPtr, this);
  }

  public void add(clustersStruct x) {
    imgdbJNI.ClusterVector_add(swigCPtr, this, clustersStruct.getCPtr(x), x);
  }

  public clustersStruct get(int i) {
    return new clustersStruct(imgdbJNI.ClusterVector_get(swigCPtr, this, i), false);
  }

  public void set(int i, clustersStruct x) {
    imgdbJNI.ClusterVector_set(swigCPtr, this, i, clustersStruct.getCPtr(x), x);
  }

}
