/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.imgseek.imgdb.core;

public class LongIntVector {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected LongIntVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(LongIntVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      imgdbJNI.delete_LongIntVector(swigCPtr);
    }
    swigCPtr = 0;
  }

  public LongIntVector() {
    this(imgdbJNI.new_LongIntVector__SWIG_0(), true);
  }

  public LongIntVector(long n) {
    this(imgdbJNI.new_LongIntVector__SWIG_1(n), true);
  }

  public long size() {
    return imgdbJNI.LongIntVector_size(swigCPtr, this);
  }

  public long capacity() {
    return imgdbJNI.LongIntVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    imgdbJNI.LongIntVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return imgdbJNI.LongIntVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    imgdbJNI.LongIntVector_clear(swigCPtr, this);
  }

  public void add(int x) {
    imgdbJNI.LongIntVector_add(swigCPtr, this, x);
  }

  public int get(int i) {
    return imgdbJNI.LongIntVector_get(swigCPtr, this, i);
  }

  public void set(int i, int x) {
    imgdbJNI.LongIntVector_set(swigCPtr, this, i, x);
  }

}
