/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.imgseek.imgdb.core;

public class bloom_filter {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected bloom_filter(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(bloom_filter obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      imgdbJNI.delete_bloom_filter(swigCPtr);
    }
    swigCPtr = 0;
  }

  public bloom_filter(long elem_cnt, double prob_fp, long rnd_sd) {
    this(imgdbJNI.new_bloom_filter__SWIG_0(elem_cnt, prob_fp, rnd_sd), true);
  }

  public bloom_filter(bloom_filter filter) {
    this(imgdbJNI.new_bloom_filter__SWIG_1(bloom_filter.getCPtr(filter), filter), true);
  }

  public void insert(int key) {
    imgdbJNI.bloom_filter_insert(swigCPtr, this, key);
  }

  public boolean contains(int key) {
    return imgdbJNI.bloom_filter_contains(swigCPtr, this, key);
  }

  public long size() {
    return imgdbJNI.bloom_filter_size(swigCPtr, this);
  }

}
