/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.imgseek.imgdb.core;

public class clustersStruct {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected clustersStruct(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(clustersStruct obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      imgdbJNI.delete_clustersStruct(swigCPtr);
    }
    swigCPtr = 0;
  }

  public void setId(SWIGTYPE_p_imageId value) {
    imgdbJNI.clustersStruct_id_set(swigCPtr, this, SWIGTYPE_p_imageId.getCPtr(value));
  }

  public SWIGTYPE_p_imageId getId() {
    return new SWIGTYPE_p_imageId(imgdbJNI.clustersStruct_id_get(swigCPtr, this), true);
  }

  public void setImgIds(LongIntVector value) {
    imgdbJNI.clustersStruct_imgIds_set(swigCPtr, this, LongIntVector.getCPtr(value), value);
  }

  public LongIntVector getImgIds() {
    long cPtr = imgdbJNI.clustersStruct_imgIds_get(swigCPtr, this);
    return (cPtr == 0) ? null : new LongIntVector(cPtr, false);
  }

  public void setDiameter(double value) {
    imgdbJNI.clustersStruct_diameter_set(swigCPtr, this, value);
  }

  public double getDiameter() {
    return imgdbJNI.clustersStruct_diameter_get(swigCPtr, this);
  }

  public clustersStruct() {
    this(imgdbJNI.new_clustersStruct(), true);
  }

}
