/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.imgseek.imgdb.core;

public class DoubleVector {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected DoubleVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DoubleVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      imgdbJNI.delete_DoubleVector(swigCPtr);
    }
    swigCPtr = 0;
  }

  public DoubleVector() {
    this(imgdbJNI.new_DoubleVector__SWIG_0(), true);
  }

  public DoubleVector(long n) {
    this(imgdbJNI.new_DoubleVector__SWIG_1(n), true);
  }

  public long size() {
    return imgdbJNI.DoubleVector_size(swigCPtr, this);
  }

  public long capacity() {
    return imgdbJNI.DoubleVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    imgdbJNI.DoubleVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return imgdbJNI.DoubleVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    imgdbJNI.DoubleVector_clear(swigCPtr, this);
  }

  public void add(double x) {
    imgdbJNI.DoubleVector_add(swigCPtr, this, x);
  }

  public double get(int i) {
    return imgdbJNI.DoubleVector_get(swigCPtr, this, i);
  }

  public void set(int i, double x) {
    imgdbJNI.DoubleVector_set(swigCPtr, this, i, x);
  }

}
